### ISSUE TITLE
when trying to install: error no .htaccess (like in xml described)

### ISSUE THREAD

**Issue by jojo12** [jemproject/plg_jem_demo#1]
I deleted then the line in xml (after it is installed)

**Comment by Heklaterriol** [comment]
the .htaccess file was gone missing during ziping the package. I added it again and uploaded [plg_jem_demo-2.1-dev007.zip](https://github.com/jemproject/plg_jem_demo/blob/main/plg_jem_demo-2.1-dev007.zip) to the repo.
